### ISSUE TITLE
Problem with graph generation with field of type Map

### ISSUE THREAD

**Issue by jlstrater** [longwa/build-test-data#106]
In a grails 3.3.3 project running build test data 3.3.0.RC2, given an entity like 
```
class Person {
   String first
   String last
   Map someOtherData
}
```

When trying to build the field of type Map in a unit test, I get the following error:

```java.lang.NullPointerException
	at grails.buildtestdata.builders.PersistentEntityDataBuilder.findRequiredDomainClasses_closure3(PersistentEntityDataBuilder.groovy:67)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at grails.buildtestdata.builders.PersistentEntityDataBuilder.findRequiredDomainClasses(PersistentEntityDataBuilder.groovy:66)
	at grails.buildtestdata.builders.PersistentEntityDataBuilder.<init>(PersistentEntityDataBuilder.groovy:53)
	at grails.buildtestdata.builders.PersistentEntityDataBuilder$Factory.build(PersistentEntityDataBuilder.groovy:31)
	at grails.buildtestdata.TestData.createBuilder(TestData.groovy:116)
	at grails.buildtestdata.TestData.findBuilder(TestData.groovy:103)
	at grails.buildtestdata.testing.DependencyDataTest$Trait$Helper.mockDependencyGraph_closure1(DependencyDataTest.groovy:34)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at grails.buildtestdata.testing.DependencyDataTest$Trait$Helper.mockDependencyGraph(DependencyDataTest.groovy:31)
	at grails.buildtestdata.testing.DependencyDataTest$Trait$Helper.mockDomains(DependencyDataTest.groovy:20)
	at grails.buildtestdata.BuildDataTest$Trait$Helper.mockDomains(BuildDataTest.groovy:19)
	at ...)
```
After debugging into the PersistentEntityDataBuilder, I was able to track the issue to this [line](https://github.com/longwa/build-test-data/blob/master/plugin/src/main/groovy/grails/buildtestdata/builders/PersistentEntityDataBuilder.groovy#L73).  If we remove values with a null value for assc.associatedEntity I suspect that will fix the problem.

**Comment by longwa** [comment]
This PR was part of the 3.3.0 release.
