### ISSUE TITLE
Exception when build an object that has unique constraint on integration test

### ISSUE THREAD

**Issue by magnomp** [longwa/build-test-data#58]
On integration test (I didn't checked for unit tests) if you build() a domain that has unique constraint, you get:
```
groovy.lang.MissingMethodException: No signature of method: org.grails.datastore.gorm.validation.constraints.UniqueConstraint$_withManualFlushMode_closure2.doCall() is applicable for argument types: (org.hibernate.internal.SessionImpl) values: [SessionImpl(<closed>)]
Possible solutions: doCall(org.grails.datastore.mapping.core.Session), findAll(), findAll(), isCase(java.lang.Object), isCase(java.lang.Object)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.grails.orm.hibernate.HibernateGormStaticApi$1.doInHibernate(HibernateGormStaticApi.groovy:176)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:198)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:142)
	at org.grails.orm.hibernate.HibernateGormStaticApi.withSession(HibernateGormStaticApi.groovy:174)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.withSession(GormEntity.groovy:700)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.withManualFlushMode(UniqueConstraint.groovy:104)
	at org.grails.datastore.gorm.validation.constraints.UniqueConstraint.processValidate(UniqueConstraint.groovy:39)
	at grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:979)
	at grails.buildtestdata.DomainInstanceBuilder.getErrors(DomainInstanceBuilder.groovy:248)
	at grails.buildtestdata.DomainInstanceBuilder.createMissingProperty(DomainInstanceBuilder.groovy:207)
	at grails.buildtestdata.DomainInstanceBuilder.populateInstance(DomainInstanceBuilder.groovy:160)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:136)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:135)
	at grails.buildtestdata.BuildTestDataService.addBuildMethods_closure1(BuildTestDataService.groovy:24)
	at groovy.lang.Closure.call(Closure.java:426)
	at demobtd.FooSpec.$tt__setup(FooSpec.groovy:14)
	at demobtd.FooSpec.setup_closure1(FooSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at demobtd.FooSpec.setup(FooSpec.groovy)
```

Using TestDataConfig.groovy to implement the generation like:
```
testDataConfig {
    sampleData {
        'demobtd.Customer' {
            def i = 1
            name = { "name${i++}" }
        }
    }
}
```
doesn't help

I'm using build-test-data 3.0.0 and Grails 3.0.11

**Comment by magnomp** [comment]
I did futher testing about this and found that you don't even need to build the instance through BTD to see the error, just having BTD on classpath and @Build() on the spec class is enough, like here:
```
@Integration
@Rollback
@Build(Customer)
class FooSpec extends Specification {

    def setup() {
        new Customer(name: "John Doe").save(failOnError: true)
    }

    def cleanup() {
    }

    void "test something"() {
        expect:"fix me"
            true == true
    }
}
```

If you comment @Build, the test passes

**Comment by tednaleid** [comment]
the `@Build` annotation is only for unit tests, it'll cause problems in integration tests and shouldn't be used there.  all your domain objects already have `build()` methods in integration tests.
