### ISSUE TITLE
IntegrationSpec Tests Thows Error using Grails 2.5.4

### ISSUE THREAD

**Issue by sdouglas28** [longwa/build-test-data#62]
We were using the plugin with our spock integrationSpec tests without any issue under grails 2.3.1 and java 7. Post an upgrade to Java 8 and grails 2.5.4 we are now receiving this error when running the tests. 

java.lang.IllegalStateException: Method on class [SomeDomainClass] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at grails.buildtestdata.DomainInstanceBuilder.save(DomainInstanceBuilder.groovy:242)
	at grails.buildtestdata.DomainInstanceBuilder.save(DomainInstanceBuilder.groovy:231)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:137)

**Comment by sdouglas28** [comment]
Human error on this one. Fixed it.
