### ISSUE TITLE
Does this plugin work with the latest GORM (hibernate5 plugin) in Grails 3.2?

### ISSUE THREAD

**Issue by rvanderwerf** [longwa/build-test-data#72]
I'm running Grails 3.2.7 and my unit tests fail with the following errors:

Domain class Site should be registered but is missing. Expression: domainClass. Values: domainClass = null
java.lang.AssertionError: Domain class Site should be registered but is missing. Expression: domainClass. Values: domainClass = null
	at grails.buildtestdata.mixin.MockDomainHelper.decorate_closure2(MockDomainHelper.groovy:100)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.buildtestdata.mixin.MockDomainHelper.decorate(MockDomainHelper.groovy:98)
	at grails.buildtestdata.mixin.BuildTestDataTestPlugin.before(BuildTestDataTestPlugin.groovy:30)
	at grails.buildtestdata.mixin.BuildTestDataTestPlugin.onTestEvent(BuildTestDataTestPlugin.groovy:22)
	at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)
	at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:264)
	at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:248)
	at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)
	at grails.test.runtime.TestRuntimeJunitAdapter.before(TestRuntimeJunitAdapter.groovy:106)
	at grails.test.runtime.TestRuntimeJunitAdapter$1$2.evaluate(TestRuntimeJunitAdapter.groovy:44)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
	at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
	at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:73)
	at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I'm doing a basic annotation on my unit test like so:
@Mock([Site])
@Build([Site])

this works fine on grails 3.0.x but I'm assuming the newer versions of gorm based on hibernate 5 don't work with this plugin?
Using the following gorm/hibernate versions:
classpath "org.grails.plugins:hibernate5:6.0.7"

compile "org.grails.plugins:hibernate5"
compile "org.hibernate:hibernate-core:5.1.2.Final"
compile "org.hibernate:hibernate-ehcache:5.1.2.Final"

**Comment by sgates** [comment]
We're using this plugin on 3.2.8 with latest gorm/hibernate, everything is fine. 3.3 on the other hand...

**Comment by longwa** [comment]
Support for Grails 3.0 through 3.2 is provided by plugin version 3.0.1.

Support for Grails 3.3 and later is provided by plugin version 3.3.0+ (currently 3.3.0.RC1)
