### ISSUE TITLE
Grails 3.3.0.M1 unable to use build-test-data

### ISSUE THREAD

**Issue by erichelgeson** [longwa/build-test-data#74]
With a simple test that just has 

```
$ grails create-app test
$ grails create-domain-class Foo
```

```groovy
void "test something"() {
    when:
    def foo = Foo.build()

    then:
    true == false
}
```

I receive this stacktrace:
```
The method [public abstract org.grails.datastore.mapping.model.PersistentEntity org.grails.datastore.mapping.model.MappingContext.getPersistentEntity(java.lang.String)] cannot be accessed before GORM has initialized
org.grails.core.exceptions.GrailsConfigurationException: The method [public abstract org.grails.datastore.mapping.model.PersistentEntity org.grails.datastore.mapping.model.MappingContext.getPersistentEntity(java.lang.String)] cannot be accessed before GORM has initialized
	at grails.core.DefaultGrailsApplication$1.invoke(DefaultGrailsApplication.java:112)
	at org.grails.core.DefaultGrailsDomainClass.verifyContextIsInitialized(DefaultGrailsDomainClass.java:142)
	at org.grails.core.DefaultGrailsDomainClass.getConstrainedProperties(DefaultGrailsDomainClass.java:349)
	at grails.buildtestdata.mixin.MockDomainHelper.findRequiredDomainTypes(MockDomainHelper.groovy:194)
	at grails.buildtestdata.mixin.MockDomainHelper.findDomainClassesToMock_closure3(MockDomainHelper.groovy:121)
	at grails.buildtestdata.mixin.MockDomainHelper.findDomainClassesToMock(MockDomainHelper.groovy:120)
	at grails.buildtestdata.mixin.MockDomainHelper.resolveClasses(MockDomainHelper.groovy:50)
	at grails.buildtestdata.mixin.BuildTestDataTestPlugin.beforeClass(BuildTestDataTestPlugin.groovy:51)
	at grails.buildtestdata.mixin.BuildTestDataTestPlugin.onTestEvent(BuildTestDataTestPlugin.groovy:19)
	at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)
	at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:264)
	at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:248)
	at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)
	at grails.test.runtime.TestRuntimeJunitAdapter.beforeClass(TestRuntimeJunitAdapter.groovy:117)
	at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:71)
	at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-core/commit/7e00092f57c86e60652ddda7a46fced63fa72159

**Comment by erichelgeson** [comment]
Verified fixed in M2, ty!
